mrniko/netty-socketio

src/main/java/com/corundumstudio/socketio/SocketIOChannelInitializer.java

This small change will allow us to implement port unification (socketio and customer tcp on a single port).

Refactored initChannel to allow subclasses customize the channel handlers

---

src/main/java/com/corundumstudio/socketio/JsonSupportWrapper.java
src/main/java/com/corundumstudio/socketio/handler/EncoderHandler.java
src/main/java/com/corundumstudio/socketio/protocol/JacksonJsonSupport.java
src/main/java/com/corundumstudio/socketio/protocol/JsonSupport.java
src/main/java/com/corundumstudio/socketio/protocol/PacketEncoder.java

fix unescaped \n, " etc in json inside packet + minor optimization

---

src/main/java/com/corundumstudio/socketio/protocol/PacketDecoder.java

fix for  https://github.com/mrniko/netty-socketio/issues/303

fix for skipping 'd=' in packet

---

src/main/java/com/corundumstudio/socketio/SocketIOChannelInitializer.java
src/main/java/com/corundumstudio/socketio/handler/ClientHead.java
src/main/java/com/corundumstudio/socketio/store/MemoryStoreFactory.java
src/main/java/com/corundumstudio/socketio/store/RedissonPubSubStore.java
src/test/java/com/corundumstudio/socketio/JoinIteratorsTest.java
src/test/java/com/corundumstudio/socketio/parser/DecoderAckPacketTest.java
src/test/java/com/corundumstudio/socketio/parser/DecoderBaseTest.java
src/test/java/com/corundumstudio/socketio/parser/DecoderEventPacketTest.java
src/test/java/com/corundumstudio/socketio/parser/EncoderAckPacketTest.java
src/test/java/com/corundumstudio/socketio/parser/EncoderEventPacketTest.java
src/test/java/com/corundumstudio/socketio/parser/PayloadTest.java

This pull request is focused on resolving occurrences of rules: 
squid:UselessImportCheck - Useless imports should be removed
You can find more information about the issue here:
http://dev.eclipse.org/sonar/rules/show/squid:UselessImportCheck
Please let me know if you have any questions.
Faisal

Code quality fix - Useless imports should be removed

---

src/main/java/com/corundumstudio/socketio/JsonSupportWrapper.java
src/main/java/com/corundumstudio/socketio/SocketIOChannelInitializer.java
src/main/java/com/corundumstudio/socketio/SocketIOServer.java
src/main/java/com/corundumstudio/socketio/ack/AckManager.java
src/main/java/com/corundumstudio/socketio/annotation/ScannerEngine.java
src/main/java/com/corundumstudio/socketio/annotation/SpringAnnotationScanner.java
src/main/java/com/corundumstudio/socketio/handler/AuthorizeHandler.java
src/main/java/com/corundumstudio/socketio/handler/ClientHead.java
src/main/java/com/corundumstudio/socketio/handler/EncoderHandler.java
src/main/java/com/corundumstudio/socketio/handler/InPacketHandler.java
src/main/java/com/corundumstudio/socketio/handler/ResourceHandler.java
src/main/java/com/corundumstudio/socketio/handler/WrongUrlHandler.java
src/main/java/com/corundumstudio/socketio/listener/DefaultExceptionListener.java
src/main/java/com/corundumstudio/socketio/protocol/JacksonJsonSupport.java
src/main/java/com/corundumstudio/socketio/transport/NamespaceClient.java
src/main/java/com/corundumstudio/socketio/transport/PollingTransport.java
src/main/java/com/corundumstudio/socketio/transport/WebSocketTransport.java

This pull request is focused on resolving occurrences of rule: 
squid:S1312 - Loggers should be private static final and should share a naming convention
You can find more information about the issue here:
http://dev.eclipse.org/sonar/rules/show/squid:S1312
Please let me know if you have any questions.
Faisal

Code quality fix - Loggers should be private static final

---

src/main/java/com/corundumstudio/socketio/JsonSupportWrapper.java
src/main/java/com/corundumstudio/socketio/SocketIOChannelInitializer.java
src/main/java/com/corundumstudio/socketio/annotation/OnConnectScanner.java
src/main/java/com/corundumstudio/socketio/handler/WrongUrlHandler.java
src/main/java/com/corundumstudio/socketio/listener/DefaultExceptionListener.java
src/main/java/com/corundumstudio/socketio/namespace/Namespace.java
src/main/java/com/corundumstudio/socketio/protocol/JacksonJsonSupport.java
src/main/java/com/corundumstudio/socketio/scheduler/HashedWheelScheduler.java
src/main/java/com/corundumstudio/socketio/scheduler/HashedWheelTimeoutScheduler.java
src/main/java/com/corundumstudio/socketio/store/RedissonStoreFactory.java
src/main/java/com/corundumstudio/socketio/store/pubsub/BaseStoreFactory.java

This pull request is focused on resolving occurrences of Sonar rule: 
squid:S1161 - @Override annotation should be used on any method overriding
You can find more information about the issue here: 
http://dev.eclipse.org/sonar/rules/show/squid:S1161
Please let me know if you have any questions.
Faisal

Code quality fix - @Override annotation should be used on any method overriding

---

src/main/java/com/corundumstudio/socketio/handler/EncoderHandler.java

Fix for #402 - see detailed information at the issue discussion.

WebSocket encoder, improved promise handling

---

src/main/java/com/corundumstudio/socketio/HandshakeData.java
src/main/java/com/corundumstudio/socketio/handler/AuthorizeHandler.java

Add local socket address for the connection #484
* add local address to HandshakeData

Add local socket address for the connection

---

src/main/java/com/corundumstudio/socketio/handler/AuthorizeHandler.java

restore sessionId from io Cookie. #505

---

src/main/java/com/corundumstudio/socketio/listener/ExceptionListenerAdapter.java

ExceptionListenerAdapter  implements an empty onPingException

ExceptionListenerAdapter implement onPingException

---

src/main/java/com/corundumstudio/socketio/ack/AckManager.java

fix concurrency issue in AckManager

Fix concurrency issue

---

src/main/java/com/corundumstudio/socketio/misc/CompositeIterable.java
src/main/java/com/corundumstudio/socketio/misc/CompositeIterator.java

Make it compatible with Spliterator/Stream in java8 by returning a new Iterator each time iterator() is called

Fix CompositeIterable

---

src/main/java/com/corundumstudio/socketio/protocol/PacketDecoder.java

according to [this comment](https://github.com/mrniko/netty-socketio/issues/760#issuecomment-647370932), this code can fix the bug of [#760 issue](https://github.com/mrniko/netty-socketio/issues/760), thanks

fix namespace bug

---

src/main/java/com/corundumstudio/socketio/BroadcastOperations.java
src/main/java/com/corundumstudio/socketio/MultiRoomBroadcastOperations.java
src/main/java/com/corundumstudio/socketio/SingleRoomBroadcastOperations.java
src/main/java/com/corundumstudio/socketio/SocketIOServer.java
src/main/java/com/corundumstudio/socketio/namespace/Namespace.java

tow hotfix:
1. #552 this pr is too long ago, I also make this hotfix.
2. In multi nodes, other nodes receive only one LEAVE msg on client disconnect, although the client had joined multi rooms.

Hotfix：multy node with redisson receive multy same message 

---

src/main/java/com/corundumstudio/socketio/Configuration.java
src/main/java/com/corundumstudio/socketio/handler/EncoderHandler.java

Solve CROS add custom headers in request

Support config ACCESS_CONTROL_ALLOW_HEADERS

---

src/main/java/com/corundumstudio/socketio/SocketConfig.java
src/main/java/com/corundumstudio/socketio/SocketIOServer.java

waterlevel config support in SocketIOServer is needed, so i can check channel status and drop the event.

in broadcast case, water level config is needed

---

pom.xml
src/main/java/com/corundumstudio/socketio/SocketIOChannelInitializer.java
src/main/java/com/corundumstudio/socketio/SocketIOServer.java
src/main/java/com/corundumstudio/socketio/listener/ClientListeners.java
src/main/java/com/corundumstudio/socketio/namespace/Namespace.java
src/main/java/com/corundumstudio/socketio/protocol/PacketDecoder.java

Fixed https://github.com/mrniko/netty-socketio/issues/848.

optimize Namespace's method ('addListeners') to support iterable

---

pom.xml

This PR makes it easier to work with socket io exports. Will fix the issue: #412 Also expose all the socket io classes to be used.

Adds all the socketio specific classes to bundles

---

src/main/java/com/corundumstudio/socketio/transport/PollingTransport.java
src/main/java/com/corundumstudio/socketio/transport/WebSocketTransport.java

fix #790 and i got another one npe in WebSocketTransport.channelRead line 117 and fix it too

fix npe in transport

---

src/main/java/com/corundumstudio/socketio/handler/AuthorizeHandler.java
src/main/java/com/corundumstudio/socketio/handler/InPacketHandler.java
src/main/java/com/corundumstudio/socketio/protocol/Packet.java
src/main/java/com/corundumstudio/socketio/protocol/PacketEncoder.java

fix https://github.com/mrniko/netty-socketio/issues/908#issue-1756569279
fix https://github.com/mrniko/netty-socketio/issues/903#issue-1737982769
fix https://github.com/mrniko/netty-socketio/issues/901#issue-1729567618
postman test  socket.io V2 V3 V4 pass
==============================
==============================
websocket demo test
================================
polling demo test
================================

fix socket.io 4.X connect issues

---

src/main/java/com/corundumstudio/socketio/BroadcastOperations.java
src/main/java/com/corundumstudio/socketio/MultiRoomBroadcastOperations.java
src/main/java/com/corundumstudio/socketio/SingleRoomBroadcastOperations.java
src/main/java/com/corundumstudio/socketio/SocketIONamespace.java
src/main/java/com/corundumstudio/socketio/SocketIOServer.java
src/main/java/com/corundumstudio/socketio/namespace/Namespace.java

- added sendEvent methods with predicate exclusion
- added BroadcastOperations get for multiple rooms at once

Broadcast features 

---

src/main/java/com/corundumstudio/socketio/protocol/PacketDecoder.java

**What's the purpose of this PR**
Fix the issue that ack response timeout cause NPE
**Which issue(s) this PR fixes:**
Fixes https://github.com/mrniko/netty-socketio/issues/947

Fix the issue that ack response timeout cause NPE

---

README.md

Realtime online piano website, using netty-socket-io since 2 years with
~2k accounts

Added multiplayer orchestra to projects using netty socketio

---

src/main/java/com/corundumstudio/socketio/scheduler/HashedWheelTimeoutScheduler.java

Fix HashedWheelTimeoutScheduler removing scheduledFutures after task

---

src/main/java/com/corundumstudio/socketio/protocol/PacketDecoder.java

the commit should resolves problem #964

add frame clear
