mrniko/netty-socketio

- src/main/java/com/corundumstudio/socketio/SocketIOChannelInitializer.java
- src/main/java/com/corundumstudio/socketio/handler/ClientHead.java
- src/main/java/com/corundumstudio/socketio/scheduler/HashedWheelTimeoutScheduler.java
Modified version of HashedWheelScheduler specially for timeouts handling.
Difference:
- handling old timeout with same key after adding new one
fixes multithreaded problem that appears in highly concurrent non-atomic sequence cancel() -> schedule()
> fix multithreaded problem with orphaned timeouts

- src/main/java/com/corundumstudio/socketio/handler/AuthorizeHandler.java
- src/main/java/com/corundumstudio/socketio/namespace/Namespace.java
Added a simple method to get all the rooms for a single namespace.
Added the ability to use the "io" cookie for the sessionId if it is present.
If there is an existing way to "list all rooms" for a given namespace, I didn't see it.  Basically I want to be able to do the following.
1. List all the namespaces.
2. List all the clients for a given namespace.
3. List all the rooms for a given namespace.
4. List all the clients in each room.
All seem in reach with the current code except the third one.  The code written seems to expose that without too much trouble.  Thoughts?
> SessionID cookie implementation, and expose the rooms?

- src/main/java/com/corundumstudio/socketio/namespace/Namespace.java
It should be removed from the map even if the client was connected to one or more rooms before disconnecting. 
Otherwise the entry will stay in memory, causing a memory leak. 
The "leave" method still makes sense for roomClients, since we don't want to delete from that map util nobody is interested in the room anymore. This leak only applies to clientRooms.
We have verified by checking how the sizes of these maps grows during frequent connect / disconnects.
> Changed how clientRooms map is cleaned up after a client leaves

- src/main/java/com/corundumstudio/socketio/annotation/ScannerEngine.java
This pull request is focused on resolving occurrences of rule: 
squid:S1201 - Methods named "equals" should override Object.equals(Object)
You can find more information about the issue here:
http://dev.eclipse.org/sonar/rules/show/squid:S1201
Please let me know if you have any questions.
Faisal
> Code quality fix - Methods named "equals" should override Object.equals(Object)

- src/main/java/com/corundumstudio/socketio/protocol/PacketDecoder.java
Fix in src/main/java/com/corundumstudio/socketio/protocol/PacketDecoder.java:
Fix parsing of binary packets in the case where the binary member's placeholder object contains the num and _placeholder members in the opposite order (num, _placeholder instead of _placeholder, num).
Some socket.io clients do this and it's valid.
> Bug fix - IllegalStateException thrown on valid binary packet when placeholder fields in opposite order

- src/main/java/com/corundumstudio/socketio/protocol/JacksonJsonSupport.java
- Allows easy overrides of Jackson internals (notably, ObjectMapper) to
easily extend JacksonJsonSupport and override with custom config
> Change Jackson support members from  private to protected

- src/main/java/com/corundumstudio/socketio/namespace/Namespace.java
When using leaveRoom, the complete clientRooms Instance get removed, which causes the SocketIOClient getAllRooms Method to returns a empty list, even when your client is still in some rooms. This doesn't harm SocketIOServer getRoomOperations Method (which still returns all clients from the given room), but harms for example the onDisconnectListener, when you override the onDisconnect Method, which than returns a empty list for the joinedRooms.
> Bug when using leaveRoom

- src/main/java/com/corundumstudio/socketio/Configuration.java
- src/main/java/com/corundumstudio/socketio/SocketIOChannelInitializer.java
The SSLContext setup retrieved most of its parameters from Configuration, except the algorithm for KeyManagerFactory, for which it used only the default one.
I have added this setting to the Configuration file and updated the SSLContext building accordingly. 
Also fixed some javadoc @param inconsistencies.
> Added option to change the SSL KeyManagerFactoryAlgorithm using Configuration.

- src/main/java/com/corundumstudio/socketio/HandshakeData.java
- src/main/java/com/corundumstudio/socketio/handler/AuthorizeHandler.java
Local addresses (io.netty.channel.local.LocalAddress) are quite useful as they don't bind to real socket address are less likely to cause unwanted side-effects with other processes for integration tests and unit tests.
Authorization for socket io clients connecting through local address failed because HandshakeData data was expecting instance of InetSocketAddress.
> Allow authorizing channels which are connected through LocalAddress

- src/main/java/com/corundumstudio/socketio/handler/EncoderHandler.java
As discussed in issue #402, I was getting the following messages: 
`WARNING: Failed to mark a promise as success because it has succeeded already: DefaultChannelPromise`
I was using the io.socket:socket.io-client:1.0.0 java client to produce these error messages.
I have tracked it down to the line marked below (by creating a patched Netty library, which logged the stack trace in detail) and applied a fix similar to commit 74234cec750427a773cb5bcecbc831f3515c6340
After applying this fix the warnings ceased.
> fix for issue #402, marking channel promise as success twice

- pom.xml
I had a java.lang.NoSuchMethodError: io.netty.util.internal.PlatformDependent.newAtomicIntegerFieldUpdater because of conflicting netty versions.
This pr updates the old(maybe forgotten) netty dependencies to 4.1.15.Final.
> Set version of netty-transport to 4.1.15.Final as well

- src/main/java/com/corundumstudio/socketio/SocketIOServer.java
The SO_LINGER option is a child channel option, not a server option - changed the bootstrapping code to do correctly. In earlier versions of Netty this was silently ignored, but in newer version (4.1.15.Final as well) a warning is shown, and also the option is ignored.
Sorry for the messed up commits, I got confused a little with the commit messages  :)
> Fix for issue #481

- src/main/java/com/corundumstudio/socketio/transport/PollingTransport.java
Cause:
- when the b64 is set as bool value like "http://<hostaddress>/socket.io/1/?EIO=2&transport=polling&b64=true",
Exception [java.lang.NumberFormatException: For input string: "true"] will throw.
Because it try to parse a string "true" to Integer.
Fix:
- take true as 1 and take false as 0
> Fix NumberFormatException when b64 is bool value.

- src/main/java/com/corundumstudio/socketio/protocol/PacketDecoder.java
Hi,
I found that there is something confusing at com.corundumstudio.socketio.protocol.PacketDecoder, it may convert some utf8 characters  to "???"
I create an [issue](https://github.com/mrniko/netty-socketio/issues/515) 
```
// TODO optimize
public ByteBuf preprocessJson(Integer jsonIndex, ByteBuf content) throws IOException {
String packet = URLDecoder.decode(content.toString(CharsetUtil.UTF_8), CharsetUtil.UTF_8.name());
if (jsonIndex != null) {
/**
* double escaping is required for escaped new lines because unescaping of new lines can be done safely on server-side
* (c) socket.io.js
*
* @see https://github.com/Automattic/socket.io-client/blob/1.3.3/socket.io.js#L2682
*/
packet = packet.replace("\\\\n", "\\n");
// skip "d="
packet = packet.substring(2);
}
packet = new …
```
> Some utf8 characters may become "???', if polling is used

- src/main/java/com/corundumstudio/socketio/handler/ClientHead.java
on ping timeout, `client.disconnect` needs to be called instead of `client.onChannelDisconnect`
> fix for underlying connection not closing on ping timeout

- src/main/java/com/corundumstudio/socketio/transport/WebSocketTransport.java
- src/test/java/com/corundumstudio/socketio/transport/WebSocketTransportTest.java
- If an endpoint receives a Close frame and did not previously send a
Close frame, the endpoint MUST send a Close frame in response.
> [#547] process websocket CloseFrame

- .gitignore
- src/main/java/com/corundumstudio/socketio/handler/ClientHead.java
- src/main/java/com/corundumstudio/socketio/transport/PollingTransport.java
release inactive long-polling channel from ClientsBox to avoid memory leak
> fix memory leak issue

- src/main/java/com/corundumstudio/socketio/transport/WebSocketTransport.java
#596
reason:
WebSocketTransport line 144 : Packet packet = new Packet(PacketType.MESSAGE); //subType =null
PacketEncoder line 288: byte subType = toChar(packet.getSubType().getValue()); //NullPointerException
fix
WebSocketTransport
Packet packet = new Packet(PacketType.MESSAGE);
packet.setSubType(PacketType.DISCONNECT);
> fix NPE  &  mem leak

- src/main/java/com/corundumstudio/socketio/protocol/PacketDecoder.java
socketio.js 2.0 + node socktio.js  -> work well
socketio.js 2.0 + netty-socketio-1.7.16 -> invalid namespace
**reason:**
namespace request payload contains url query string info, like 
`8:40/chat,`
`49:40/chatroom?uid=ba7822bee25940ada9d2a987670afc5d,`
it does'n match `/chat` or `/chatroom` in namespacehub
**fix:** 
before `packet.setNsp`, sub the query string
> fix invalid namespace

- src/main/java/com/corundumstudio/socketio/protocol/Packet.java
- src/main/java/com/corundumstudio/socketio/transport/NamespaceClient.java
- src/test/java/com/corundumstudio/socketio/protocol/PacketTest.java
Given mutable nature of Packet object and a fact that single Packet
instance is created in BroadcastOperations before sending it to all
clients, when event is emitted to room where clients with different
namespaces are joined, then all of them will receive that event on
single namespace.
By using withNs method, Packet copy will be created, effectively, solving
the issue
> Fix cross-namespace broadcast happens on single ns

- src/main/java/com/corundumstudio/socketio/SocketIOServer.java
- src/main/java/com/corundumstudio/socketio/listener/ClientListeners.java
- src/main/java/com/corundumstudio/socketio/listener/EventInterceptor.java
- src/main/java/com/corundumstudio/socketio/namespace/Namespace.java
continue of - https://github.com/mrniko/netty-socketio/pull/465
> Add support for event interceptors which catch all events

- src/main/java/com/corundumstudio/socketio/protocol/Event.java
In order to create custom serialization code (using `JsonSupport`) I need to be able to create `Event` instances
> Make "Event" class public

- src/main/java/com/corundumstudio/socketio/annotation/SpringAnnotationScanner.java
When I use @PostConstruct init other bean in EventListener, the originalBeanClass not match dest bean;
The EventBean:
`
@Component
public class TrainOnlineSocket {
private IMongoHoursService mongoHoursService;
@PostConstruct
public void init() {
if (mongoHoursService == null) {
// init mongoHoursService Bean; The bean not may be init before this bean
mongoHoursService = SpringContextUtil.getBean(IMongoHoursService.class);
}
// other business
}
@OnEvent(SocketEvent.TRANING_ONLINE)
public void pushOnlineEvent(SocketIOClient client, PushMessage<PushMessageContentForm> data, AckRequest ackRequest) 
// other business
}
}
`
Now...
`
public class SpringAnnotationScanner implements BeanPostProcessor {
@Override
public Object postProcessAfterInitialization(Object bean, String beanName) throws …
> fixed event listener src class and dest bean is nott  match

- src/main/java/com/corundumstudio/socketio/Transport.java
- src/main/java/com/corundumstudio/socketio/handler/AuthorizeHandler.java
Hello! 
I have tried to fix small bug on connect with missing or invalid transport parameter.
This [Socket.io docs](https://socket.io/docs/v3/troubleshooting-connection-issues/) describe expected behavior.
> In case of an HTTP 400 response, the response payload will be one of the following:
> `{"code":0,"message":"Transport unknown"}`
> The transport query parameter is missing or invalid.
> To reproduce: curl "<url>/socket.io/" or curl "<url>/socket.io/?transport=udp"
**On curl with wrong transport:**
`
curl http://localhost:9092/socket.io/?transport=udp
//keeping connection
`
**on log:**
`
[nioEventLoopGroup-3-1] WARN io.netty.channel.DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the …
> Fixed bug on illegal transport parameter

- src/main/java/com/corundumstudio/socketio/SocketIOClient.java
- src/main/java/com/corundumstudio/socketio/namespace/Namespace.java
- src/main/java/com/corundumstudio/socketio/transport/NamespaceClient.java
```
public Iterable<SocketIOClient> getRoomClients(String room) {
//This value is the total number of clients in the current room in the cluster
Set<UUID> sessionIds = roomClients.get(room);
if (sessionIds == null) {
return Collections.emptyList();
}
//At this time, the clients that are not in the current server in the current room are filtered out
List<SocketIOClient> result = new ArrayList<SocketIOClient>();
for (UUID sessionId : sessionIds) {
SocketIOClient client = allClients.get(sessionId);
if(client != null) {
result.add(client);
}
}
//So the number of clients in the current room I get is only for the current server, not for the entire cluster
return result;
}
```
> Get the number of clinets in a room in a cluster environment

- src/main/java/com/corundumstudio/socketio/Configuration.java
- src/main/java/com/corundumstudio/socketio/SocketIOChannelInitializer.java
This fixes issue #503, by exposing a client auth option for TLS connections.  When configured, client connection attempts are rejected unless they present a certificate allowed by the trust store.  If no trust store is configured, the setting has no effect.
> Expose client auth option

- src/main/java/com/corundumstudio/socketio/handler/ClientHead.java
move ping scheduling to be conditional on a client still existing
cancel existing scheduled ping and ping timeouts before scheduling another
> fix some possible leaks in the new ping/pong code refs #868

- src/main/java/com/corundumstudio/socketio/SocketIOClient.java
- src/main/java/com/corundumstudio/socketio/namespace/Namespace.java
- src/main/java/com/corundumstudio/socketio/store/pubsub/BaseStoreFactory.java
- src/main/java/com/corundumstudio/socketio/store/pubsub/BulkJoinLeaveMessage.java
- src/main/java/com/corundumstudio/socketio/store/pubsub/PubSubType.java
- src/main/java/com/corundumstudio/socketio/transport/NamespaceClient.java
We have a large number of rooms a socket client can subscribe to, and when a client connects to our server, we pull all the rooms they were previously subscribed to from our backend and issue a join request for all the rooms, this also ends up issuing a publish on pubsub (async wrapper over RedissonPubSubStore in our case) for JOIN / LEAVE events 
This is causing high CPU spikes
Added a bulk JOIN / LEAVE API to allow the above use case to be handled in a more efficient manner for us. This will allow client to join a large number of rooms at the same time without causing a lot of resource strain
> Added support for bulk join and leave

- src/main/java/com/corundumstudio/socketio/SocketIOClient.java
- src/main/java/com/corundumstudio/socketio/handler/ClientHead.java
- src/main/java/com/corundumstudio/socketio/transport/NamespaceClient.java
socketIOClient support method isWritable(), avoid DirectByteBuffer oom when the channel is not writable.
> client support method isWritable(), avoid DirectByteBuffer oom

- src/main/java/com/corundumstudio/socketio/AuthTokenListener.java
- src/main/java/com/corundumstudio/socketio/AuthTokenResult.java
- src/main/java/com/corundumstudio/socketio/AuthorizationListener.java
- src/main/java/com/corundumstudio/socketio/HandshakeData.java
- src/main/java/com/corundumstudio/socketio/SocketIONamespace.java
- src/main/java/com/corundumstudio/socketio/handler/EncoderHandler.java
- src/main/java/com/corundumstudio/socketio/handler/InPacketHandler.java
- src/main/java/com/corundumstudio/socketio/listener/DefaultExceptionListener.java
- src/main/java/com/corundumstudio/socketio/listener/ExceptionListener.java
- src/main/java/com/corundumstudio/socketio/namespace/Namespace.java
- src/main/java/com/corundumstudio/socketio/protocol/PacketDecoder.java
- src/main/java/com/corundumstudio/socketio/protocol/PacketEncoder.java
This PR adds support for the [auth data feature](https://socket.io/docs/v4/middlewares/#sending-credentials) in Socket.IO v3.  I would have preferred to fold this into the current AuthorizationListener but they activate at different times in the connection lifetime and I didn't feel comfortable making these deep changes without aligning first.
The current implementation allows reading the auth data and then updating the client. Since this is only available for namespaces I have added the listener only to SocketIONamespace and not ClientListeners.
This also fixes the connection_error data read error when Socket IO v3/4 expect multiple packets in one. There is a delimiter char \x1e that is expected as a separator when multiple packets are sent in one response: …
> Add more Socket.IO v3/v4 features: auth data, multi-packet separator

- src/main/java/com/corundumstudio/socketio/handler/EncoderHandler.java
When instantiating the Manifest object, we open an InputStream via the openStream() function, but it is not closed. 
This issue was resolved with a try-with-resource approach where we instantiate the inputStream object in the try header, and use that for the Manifest constructor
> Resource Leak Fix with try-with-resource block in readVersion()

- src/main/java/com/corundumstudio/socketio/namespace/Namespace.java
We were on a rather old version of this library, so ran into https://github.com/mrniko/netty-socketio/issues/668, saw the issue was open so tried a fix, which worked for us
Checked the later version and found that this was fixed in commit 452870d6, but the issue with the current approach is it issues leave event one by one for all the joined rooms, which puts a lot of stress on pubsub store if there are a lot of joined rooms.
Due to the above issue we had high CPU spikes, and had added this feature https://github.com/mrniko/netty-socketio/pull/873, a little while back.
Thinking of leveraging that here to send leave event for all the joined rooms at once, to reduce the stress on pubsub store.
Few possible solutions, that I can think of
1. Do a bulk leave beforehand, as joinedRooms set gets …
> Send Bulk leave event instead of multiple leave events on disconnect

- src/main/java/com/corundumstudio/socketio/protocol/PacketDecoder.java
I found that the existing auth data support function is only for the default namespace, so I made some modifications so that all custom namespaces support auth data. @mrniko
> Make custom namespaces support auth data

- src/main/java/com/corundumstudio/socketio/transport/WebSocketTransport.java
Proposed tweak to #987 in order to allow future reconnections in case of recoverable handshake failure
> Only remove first time handshake failures

- src/main/java/com/corundumstudio/socketio/Configuration.java
- src/main/java/com/corundumstudio/socketio/HttpRequestDecoderConfiguration.java
- src/main/java/com/corundumstudio/socketio/SocketIOChannelInitializer.java
This PR contains http request decoder configuration
Resolves: #1003
> io.netty.handler.codec.http.TooLongHttpLineException: An HTTP line is larger than 4096 bytes.

- src/main/java/com/corundumstudio/socketio/namespace/Namespace.java
- Add a check to the onConnect method to prevent clients from joining the same namespace twice
- Optimized namespace connection logic to improve system stability
> fix(namespace): prevents the client from repeatedly connecting to the namespace

- src/main/java/com/corundumstudio/socketio/protocol/PacketDecoder.java
This PR updates the handling of attachments on events.
Resolves: https://github.com/mrniko/netty-socketio/issues/706
Context:
When encountaring binary data, the client sets a number of placeholders in the first package and then sends the actual data in the packets following it without additional info prepended.
although they state [here](https://github.com/socketio/socket.io-protocol?tab=readme-ov-file#packet-encoding) that 
`each Socket.IO packet is wrapped in a Engine.IO message packet, so they will be prefixed by the character "4" when sent over the wire.`
it does not seem to apply to [attachements](https://github.com/socketio/socket.io-protocol/blob/4f633dd6a4445492d57af3b27ddd2d336014f1f1/test-suite/test-suite.js#L565), as seen in this example:
```
socket.send( …
```
> fix: treat attachments as binary by default
